export const SET_ADMIN_PROPS = "SET_ADMIN_PROPS";
export const SET_PACK_PRICES = "SET_PACK_PRICES";
export const SET_EXTENDED_COUNT = "SET_EXTENDED_COUNT";
export const SET_GEM_PACKS = "SET_GEM_PACKS";
export const SET_USER_PACKS = "SET_USER_PACKS";
export const SET_BULK_PLANS = "SET_BULK_PLANS";
export const SET_SPARK_FAILURE = "SET_SPARK_FAILURE";
