export const SET_CURRENT_SCREEN_INDEX = "SET_CURRENT_SCREEN_INDEX";
export const SET_CHAT_CURRENT_SCREEN_INDEX = "SET_CHAT_CURRENT_SCREEN_INDEX";
export const SET_CURRENT_RESPONSES = "SET_CURRENT_RESPONSES";

export const CLEAR_CURRENT_RESPONSES = "CLEAR_CURRENT_RESPONSES";
export const SCROLL_TO_QUESTION_CARD = "SCROLL_TO_QUESTION_CARD";
export const DELETE_CONTENT = "DELETE_CONTENT";

export const OPEN_FIRST_CARD_DIRECTLY = "OPEN_FIRST_CARD_DIRECTLY";
export const SET_QUESTION_CARD_VISIBILITY = "SET_QUESTION_CARD_VISIBILITY";
export const SET_QUESTION_CARD_TUTORIAL_VISIBILITY = "SET_QUESTION_CARD_TUTORIAL_VISIBILITY";

export const SHARE_CONTENT = "SHARE_CONTENT";
export const SHOW_CLOSER_POPOVER = "SHOW_CLOSER_POPOVER";
export const POST_USER_QUESTION_CONTENT = "POST_USER_QUESTION_CONTENT";

export const PUSH_UPLOADING_IMAGE_MSGID = "PUSH_UPLOADING_IMAGE_MSGID";
export const SET_UPLOADING_MSGIMAGE_STATUS = "SET_UPLOADING_MSGIMAGE_STATUS";

export const SET_NOTIFICATION_PERMISSION = "SET_NOTIFICATION_PERMISSION";
export const SET_LOCATION_PERMISSION = "SET_LOCATION_PERMISSION";

export const SET_FIREBASE_NOTIFICATION ="SET_FIREBASE_NOTIFICATION"

export const SET_OPTION_FADE_ANIMATION ="SET_OPTION_FADE_ANIMATION"