export const SET_THIRTY_PROFILES = "SET_THIRTY_PROFILES";
export const SET_CURRENT_PROFILE_INDEX = "SET_CURRENT_PROFILE_INDEX";
export const SET_HAS_MORE = "SET_HAS_MORE";
export const SET_CREATED_AT = "SET_CREATED_AT";
