export const SET_MY_CARD_SEEN_COUNT = "SET_MY_CARD_SEEN_COUNT";
export const SET_OTHERS_CARD_SEEN_COUNT = "SET_OTHERS_CARD_SEEN_COUNT";
export const SET_QUESTION_PICKER_SEEN_COUNT = "SET_QUESTION_PICKER_SEEN_COUNT";
export const SET_EXPENSES_TUTORIALS = "SET_EXPENSES_TUTORIALS";
export const SET_TUTORIAL_ROOM = "SET_TUTORIAL_ROOM";

export const SET_PROFILE_CARDS_TUTORIAL = "SET_PROFILE_CARDS_TUTORIAL";
export const SET_REACT_BUTTON_TUTORIAL = "SET_REACT_BUTTON_TUTORIAL";

export const SET_SENT_SECTION_TUTORIAL_VISIBILITY =
  "SET_SENT_SECTION_TUTORIAL_VISIBILITY";
export const SET_RECEIVED_SECTION_TUTORIAL_VISIBILITY =
  "SET_RECEIVED_SECTION_TUTORIAL_VISIBILITY";
export const SET_FRIENDS_SECTION_TUTORIAL_VISIBILITY =
  "SET_FRIENDS_SECTION_TUTORIAL_VISIBILITY";

export const SET_CHATBOX_PICKER_VISIBILITY = "SET_CHATBOX_PICKER_VISIBILITY";
export const SET_CLOSER_POPUP_VISIBILITY = "SET_CLOSER_POPUP_VISIBILITY";
export const SET_PRESET_CONTENT_MODAL_VISIBILITY =
  "SET_PRESET_CONTENT_MODAL_VISIBILITY";

  export const SET_REACT_ON_THESE_CARDS_TUTORIAL_VISIBILITY = "SET_REACT_ON_THESE_CARDS_TUTORIAL_VISIBILITY";
export const SET_CRON_REQUEST_CRON = "SET_CRON_REQUEST_CRON";
export const SET_RESPONSE_CRON = "SET_RESPONSE_CRON";

export const SET_REFERRAL_CODE = "SET_REFERRAL_CODE";

export const SET_TUTORIAL_BEGIN_TIME = "SET_TUTORIAL_BEGIN_TIME";
export const SET_TOP_NAV_TAB_TUTORIALS_SEEN = "SET_TOP_NAV_TAB_TUTORIALS_SEEN";
export const SET_ONCE_SENT_STACK_TUTORIAL_SEEN =
  "SET_ONCE_SENT_STACK_TUTORIAL_SEEN";
export const SET_ONCE_RECEIVED_STACK_TUTORIAL_SEEN =
  "SET_ONCE_RECEIVED_STACK_TUTORIAL_SEEN";
